services:
  web:
    build: .
    env_file: .env
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=wsgi.py
      - DATABASE_URL=postgresql://custom_user:strong_password@db:5432/catalog_db
      - SQLALCHEMY_DATABASE_URI=postgresql://custom_user:strong_password@db:5432/catalog_db
      - FLASK_ENV=production
      - MINIO_ACCESS_KEY=minioaccess
      - MINIO_SECRET_KEY=miniosecret
      - MINIO_BUCKET=documents
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - minio

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_USER: custom_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: catalog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U custom_user -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minioaccess
      - MINIO_SECRET_KEY=miniosecret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  celery-worker:
    build: .
    command: celery -A tasks.celery_app worker -Q document_processing,analysis --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - DROPBOX_FOLDER_PATH=${DROPBOX_FOLDER_PATH}
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - DROPBOX_FOLDER_PATH=${DROPBOX_FOLDER_PATH}
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
      - celery-worker

  celery:
    build: .
    command: celery -A tasks.celery_app worker -Q celery --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - DROPBOX_FOLDER_PATH=${DROPBOX_FOLDER_PATH}
    depends_on:
      - redis
      
volumes:
  postgres_data:
  minio_data:
  redis_data: